version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "28017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: classmate
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
